config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/failure'

  get 'welcome/index'
  root 'plans#index'

  #devise_for :users
  resources :plans
  resources :kpis
  resources :kactions

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]



end

app/models/kpi.rb
class Kpi < ActiveRecord::Base
end

app/controllers/kpis_controller.rb
class KpisController < ApplicationController
  before_action :set_kpi, only: [:show, :edit, :update, :destroy]

  # GET /kpis
  # GET /kpis.json
  def index
    @kpis = Kpi.all
  end

  # GET /kpis/1
  # GET /kpis/1.json
  def show
  end

  # GET /kpis/new
  def new
    @kpi = Kpi.new
  end

  # GET /kpis/1/edit
  def edit
  end

  # POST /kpis
  # POST /kpis.json
  def create
    @kpi = Kpi.new(kpi_params)

    respond_to do |format|
      if @kpi.save
        format.html { redirect_to @kpi, notice: 'Kpi was successfully created.' }
        format.json { render :show, status: :created, location: @kpi }
      else
        format.html { render :new }
        format.json { render json: @kpi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kpis/1
  # PATCH/PUT /kpis/1.json
  def update
    respond_to do |format|
      if @kpi.update(kpi_params)
        format.html { redirect_to @kpi, notice: 'Kpi was successfully updated.' }
        format.json { render :show, status: :ok, location: @kpi }
      else
        format.html { render :edit }
        format.json { render json: @kpi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kpis/1
  # DELETE /kpis/1.json
  def destroy
    @kpi.destroy
    respond_to do |format|
      format.html { redirect_to kpis_url, notice: 'Kpi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kpi
      @kpi = Kpi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kpi_params
      params.require(:kpi).permit(:description, :responsibility, :milestone)
    end
end

app/helpers/kpis_helper.rb
module KpisHelper
end

app/views/kpis/_form.html.erb
<%= form_for(@kpi) do |f| %>
  <% if @kpi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kpi.errors.count, "error") %> prohibited this kpi from being saved:</h2>

      <ul>
      <% @kpi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :responsibility %><br>
    <%= f.text_field :responsibility %>
  </div>
  <div class="field">
    <%= f.label :milestone %><br>
    <%= f.text_field :milestone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kpis/edit.html.erb
<h1>Editing Kpi</h1>

<%= render 'form' %>

<%= link_to 'Show', @kpi %> |
<%= link_to 'Back', kpis_path %>

app/views/kpis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Kpis</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kpis.each do |kpi| %>
      <tr>
        <td><%= kpi.description %></td>
        <td><%= kpi.responsibility %></td>
        <td><%= kpi.milestone %></td>
        <td><%= link_to 'Show', kpi %></td>
        <td><%= link_to 'Edit', edit_kpi_path(kpi) %></td>
        <td><%= link_to 'Destroy', kpi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kpi', new_kpi_path %>

app/views/kpis/new.html.erb
<h1>New Kpi</h1>

<%= render 'form' %>

<%= link_to 'Back', kpis_path %>

app/views/kpis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>KPI:</strong>
  <%= @kpi.description %>
</p>

<p>
  <strong>Responsibility:</strong>
  <%= @kpi.responsibility %>
</p>

<p>
  <strong>Milestone:</strong>
  <%= @kpi.milestone %>
</p>

<%= link_to 'Edit', edit_kpi_path(@kpi) %> |
<%= link_to 'Back', kpis_path %>