config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/failure'

  get 'welcome/index'
  root 'plans#index'

  #devise_for :users
  resources :plans
  resources :kpis
  resources :kactions

  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]



end

app/controllers/kactions_controller.rb
class KactionsController < ApplicationController
  before_action :set_kaction, only: [:show, :edit, :update, :destroy]

  # GET /kactions
  # GET /kactions.json
  def index
    @kactions = Kaction.all
  end

  # GET /kactions/1
  # GET /kactions/1.json
  def show
  end

  # GET /kactions/new
  def new
    @kaction = Kaction.new
  end

  # GET /kactions/1/edit
  def edit
  end

  # POST /kactions
  # POST /kactions.json
  def create
    @kaction = Kaction.new(kaction_params)

    respond_to do |format|
      if @kaction.save
        format.html { redirect_to @kaction, notice: 'Action was successfully created.' }
        format.json { render :show, status: :created, location: @kaction }
      else
        format.html { render :new }
        format.json { render json: @kaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kactions/1
  # PATCH/PUT /kactions/1.json
  def update
    respond_to do |format|
      if @kaction.update(kaction_params)
        format.html { redirect_to @kaction, notice: 'Action was successfully updated.' }
        format.json { render :show, status: :ok, location: @kaction }
      else
        format.html { render :edit }
        format.json { render json: @kaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kactions/1
  # DELETE /kactions/1.json
  def destroy
    @kaction.destroy
    respond_to do |format|
      format.html { redirect_to kactions_url, notice: 'Action was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kaction
      @kaction = Kaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kaction_params
      params.require(:kaction).permit(:description, :target)
    end
end

app/helpers/kactions_helper.rb
module KactionsHelper
end

app/views/kactions/_form.html.erb
<%= form_for(@kaction) do |f| %>
  <% if @kaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kaction.errors.count, "error") %> prohibited this kaction from being saved:</h2>

      <ul>
      <% @kaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kactions/edit.html.erb
<h1>Editing Action</h1>

<%= render 'form' %>

<%= link_to 'Show', @action %> |
<%= link_to 'Back', actions_path %>

app/views/kactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Actions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kactions.each do |kaction| %>
      <tr>
        <td><%= kaction.description %></td>
        <td><%= kaction.target %></td>
        <td><%= link_to 'Show', kaction %></td>
        <td><%= link_to 'Edit', edit_kaction_path(kaction) %></td>
        <td><%= link_to 'Destroy', kaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kaction', new_kaction_path %>

app/views/kactions/new.html.erb
<h1>New Action</h1>

<%= render 'form' %>

<%= link_to 'Back', kactions_path %>

app/views/kactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_kaction_path(@action) %> |
<%= link_to 'Back', kactions_path %>